# Auto-increment Flutter app build number before release builds.
# Updates pubspec.yaml and lib/generated/app_version.dart.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts\bump_version.ps1

$ErrorActionPreference = 'Stop'

$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$Pubspec = Join-Path $Root 'pubspec.yaml'
$VersionFile = Join-Path $Root 'lib\generated\app_version.dart'

$content = Get-Content $Pubspec -Raw
if ($content -notmatch '(?m)^version:\s*([0-9]+)\.([0-9]+)\.([0-9]+)\+([0-9]+)\s*$') {
    throw "Could not parse version from pubspec.yaml"
}

$major = [int]$Matches[1]
$minor = [int]$Matches[2]
$patch = [int]$Matches[3]
$build = [int]$Matches[4] + 1

$name = "$major.$minor.$patch"
$newLine = "version: $name+$build"
$content = [regex]::Replace($content, '(?m)^version:\s*.+$', $newLine, 1)
Set-Content -Path $Pubspec -Value $content -NoNewline

$genDir = Split-Path $VersionFile
New-Item -ItemType Directory -Force -Path $genDir | Out-Null
@(
    '// GENERATED by scripts/bump_version.ps1 — do not edit manually.',
    'abstract final class AppVersion {',
    "  static const String name = '$name';",
    "  static const int build = $build;",
    "  static String get label => '`$name+`$build';",
    "  static String get display => '`$name (build `$build)';",
    '}',
    ''
) | Set-Content -Path $VersionFile -Encoding UTF8

Write-Host "Bumped app version to $name+$build"
